#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10
#bspc monitor HDMI-1 -d I II III IV V
#bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# start polybar
bash /usr/local/bin/start-polybar.sh &

# set background
feh --bg-center ~/.local/share/wallpapers/archlinux.jpg

# start picom
picom -b
