source ~/.config/zsh/xkcd.zsh
source ~/.config/zsh/paclog.zsh

neofetch
xkcd newest

source ~/.config/zsh/oh-my-zsh.zsh


# User configuration

# enable more completion capability, including personal completions
# for some reason this does not seem to be done by omz
fpath=($fpath ~/.config/zsh/completions)
autoload -U compinit && compinit

# cache completions for better speed
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "~/.cache/zsh/.zcompcache"

# globbing options
setopt extendedglob
setopt GLOBSTARSHORT

# make cd keep a dir stack
setopt autopushd

# disable cd-ing to a dir given on its own with out `cd`
unsetopt auto_cd

# set nvim for editors
export EDITOR=nvim
export SUDO_EDITOR=nvim

# history optionss
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=50000
export SAVEHIST=50000
setopt appendhistory
#setopt hist_find_no_dups	# do not show duplicates when stepping through history
#setopt hist_ignore_all_dups	# do not save duplicates to HISTFILE

# set colors for exa, see https://github.com/ogham/exa/blob/master/man/exa_colors.5.md
export EXA_COLORS="di=33;1:su=1;4:sf=1:4"

source ~/.config/zsh/aliases.zsh

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
